export const SEARCH_INPUT = 'SEARCH_INPUT';
export const SORT_SELECT = 'SORT_SELECT';
export const BRAND_FILTERS = 'BRAND_FILTERS';
export const BRAND_ALL_FILTERS = 'BRAND_ALL_FILTERS';
export const CATEGORY_FILTERS = 'CATEGORY_FILTERS';
export const CATEGORY_ALL_FILTERS = 'CATEGORY_ALL_FILTERS';
export const GRID_STYLE = 'GRID';
