export const SEARCH_INPUT = 'T2STON_SEARCH_INPUT';
export const SORT_SELECT = 'T2STON_SORT_SELECT';
export const BRAND_FILTERS = 'T2STON_BRAND_FILTERS';
export const BRAND_ALL_FILTERS = 'T2STON_BRAND_ALL_FILTERS';
export const CATEGORY_FILTERS = 'T2STON_CATEGORY_FILTERS';
export const CATEGORY_ALL_FILTERS = 'T2STON_CATEGORY_ALL_FILTERS';
export const SHOW_CATEGORIES = 'T2STON_SHOW_CATEGORIES';
export const SHOW_BRANDS = 'T2STON_SHOW_BRANDS';
export const GRID_STYLE = 'T2STON_GRID';
export const MIN_STOCK = 'T2STON_MIN_STOCK';
export const MAX_STOCK = 'T2STON_MAX_STOCK';
export const MIN_PRICE = 'T2STON_MIN_PRICE';
export const MAX_PRICE = 'T2STON_MAX_PRICE';
export const CART_ITEMS = 'T2STON_CART_ITEMS';



export const PRODUCTS_PER_PAGE = 'PRODUCTS_PER_PAGE';

export const TH = ['№', 'Product', 'Price', 'Quantity', 'Total', 'Action'];
